language: node_js
node_js:
   - 0.8


services:
  - couchdb

before_script:
  - npm install kanso -g
  - npm install mocha -g
  - npm install grunt -g
  - npm install
  - curl -X PUT localhost:5984/garden-core


script: "grunt lint mochaTest kanso qunit --debug"


notifications:
  email:
    - ryan.ramage@gmail.com
