language: node_js
node_js:
   - 0.8


services:
  - couchdb

before_script:
  - npm install

script: "./bin/garden-core http://garden20.com/market/details/answers"


notifications:
  email:
    - ryan.ramage@gmail.com
