language: node_js

node_js:
   - 0.8

services:
  - couchdb

before_script:
  - npm install

script: "npm test && mocha --timeout 30000 test/install-travis-test.js"

notifications:
  email:
    - dev@medicmobile.org
    - ryan.ramage@gmail.com
